---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: networking
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      logLevel: INFO
      crowdsecMode: stream
      crowdsecLapiScheme: https
      crowdsecLapiHost: crowdsec-service.security.svc.cluster.local:8080
      crowdsecLapiKey: "${SECRET_CROWDSEC_TRAEFIK_BOUNCER_KEY}"
      crowdsecLapiTlsInsecureVerify: true
      updateIntervalSeconds: 60
      updateMaxFailure: -1
      defaultDecisionSeconds: 60
      forwardedHeadersTrustedIPs:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
