---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "${SECRET_TAILSCALE_EXTERNAL_HOME_DNS}"
  name: external-home-tailscale
spec:
  externalName: placeholder-external-home
  type: ExternalName
