---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-finance-vis
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-firefly-iii
  path: ./kubernetes/apps/production/finance/finance-vis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-source
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: finance-vis
      namespace: finance
  interval: 30m
  retryInterval: 1m
  timeout: 5m
