apiVersion: v1
kind: Secret
metadata:
    name: kek
type: Opaque
stringData:
    kek: ENC[AES256_GCM,data:J46C2Iy+3UDd8ha0Phz3lIxqGfVBLrJgDULPUDvU4nuHumxibyib3VqiUcY=,iv:Sr8wc+paSj2VQrutXSZAa+IOmVf7p71A5h1VoWeyLrM=,tag:NBUnd5vknS/ziNwjL274HA==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVzMzOURCeU42aDM5clpK
            WnFRRk9TT2V0dUMvWkxlb3Y0RWtURDhONkFnClFqRmtYeUdmcWxycytNS01DaW1N
            UzNUNUtPd1lCOWZBQ2EvT3UwV0t1U3MKLS0tIHk3dHA2d2pQRkRVRGpDQmlCTmpP
            WjZrUUgwK2MxODBzNWlIeVZIeWFKN2cKMu0gDiA7Ruxf9lIOerT1mWS0kX3U7Q7l
            7gTw2cdCdMUjHlrOG1YEMxMs/kvHGeULY1U9e8jeTUWRgwjZbGeEbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T19:34:39Z"
    mac: ENC[AES256_GCM,data:NUusy/KnA+QpINxY7rPc6T5rFRULojgtAJMObSP+Rwzyza8P7ax+2HN7SPQ8ThyBjZYXK+eRLbB9+akMOJP4eqdJ7s50DVmf3fgZ7948oWAGQWwBNSuSJ8ZAgzjXNXeS0XtLkm0y+oH5VF1SC8ozcy5QyvUFUEARO2ZX0y1OG5E=,iv:FVUOB8vt/n1NoLTBwGml1Z3clicGCK+Nb3wiGI/QO60=,tag:ripQWocyY46Uv5NRO4lyBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
