apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xyZA5m8g,iv:+f6LHWmDIYEYXbw8zf4eXQIIZX9lyQazvDEJSHWoUpE=,tag:NZS2bEasPyudUCKCdKrIww==,type:str]
    password: ENC[AES256_GCM,data:hkCSuV9jLLgvgU7nvxwwKw==,iv:C9C/aL0CBvKLnnqWvq7GN/2l1wE5CT1xV1LNwCqw4Ew=,tag:jIgzc0cKZKJXlinUARq7nQ==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MXlnKzM4R1RpeTBKZXdY
            UEZpSDNzZk1BUktaRGY1dTF0SjBxWFh5WUY4Ck9oaDljTHlnWkZiT0JMcDlBUkx4
            eVluWXFqTVJtUis2bldvNlZXQUp5QzgKLS0tIHorTU45RzBpdkg4ZDdMWmNvemU5
            dEZkRWxMNTlzSCt0bEdaZzNJRjFVdU0KALMMkSNS/YFrJFeLqICBPBvRhPfcxpFV
            8txkdD3H5liB5WOed8FrViBy/xkd4O6WgpsxIm4JWalgmwuqzVylNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T05:54:13Z"
    mac: ENC[AES256_GCM,data:IHRd9T4Wn4Xlg5HAxZJcWwZ4LVkr5kpodn3laE5PmmJbCsfruE+NsovMOO9cZMwuLZX04RyVAPvGm4V8tgYdXhyV2S01hh2DhtQv/23PE1jkitmz0m1+fH096UBmujoY4aN+4iBsOoigdrSHRv073UOL1swSjESrqXpJViVw1Pg=,iv:CABI34ILv4H1ngEpPy0RFGFx6RiKgw75MfCFrvVFmdQ=,tag:muSRsqStcNSGlWdoAWc+9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
