---
apiVersion: v1
kind: Service
metadata:
  name: clamav
  labels:
    app.kubernetes.io/name: clamd
    app.kubernetes.io/part-of: clamav
spec:
  selector:
    app.kubernetes.io/name: clamd
  ports:
    - name: clamd
      port: 3310
      targetPort: clamd
      protocol: TCP
