---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ./clamd-configmap.yaml
  - ./clamd-deployment.yaml
  - ./clamd-service.yaml
  - ./mirror-secret.sops.yaml
  - ./mirror-pvc.yaml
  - ./mirror-cronjob.yaml
