apiVersion: v1
kind: Secret
metadata:
    name: clamav-mirror-nexus
stringData:
    NEXUS_USER: ENC[AES256_GCM,data:DEj6hSv1MkulhfRJpQ==,iv:pOgatQht++QLFeb2GpK4aGXh7x/waZyCgM0J2XU+wOo=,tag:Yy8GaONkjBd1CEdAzTwoZw==,type:str]
    NEXUS_PASS: ENC[AES256_GCM,data:6mmwzn2HNykk+5BZiHE8xUS8ZV2vUsyd,iv:S3dKJ4OMrPxRrxa3ry9C1lYUJccvvZTWaOCwFrQdUj8=,tag:n2PxcHlqANP0QsStv77wcw==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb3JrSGt2eFNBeE05K2tY
            MEh6VUtMOVpSZ2FXT3cwY2Z3RFp0MkNTWXcwCjRXQlkzdWlVbTFhdHNmZmNzT201
            dGJUa0RaOVhBSm1qaFJIZDFXdnc0NEkKLS0tIENsMVdTVVJMK24vaEQrbVBoN1Vr
            OWVDTlhNekNpdGhkSVg1MHFpb1NCZXMKcot0v0i4tPJGupIvG8Och/Kw0fZaTm6f
            sUtCtA32930QspLRoVrHtnEl1TYOA/+gVFp7X0GB5LN4vs2tNi6DLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T21:16:51Z"
    mac: ENC[AES256_GCM,data:ZaOjgEBQnwh2u3j9PV7LxTIwxPsibyIHLzbZDEAASWVhSx2SB0HFdN31VBEQ4Iy/8+Y1Kkz7u3sCk7nYhboqROF6kUyYFJEpXrc8j+glSMsoOPDntin7jdgZDXjx8FWITx7c+i9qm1uAOsCUuo+8ed//qAd18R20NrDWlxsYiW0=,iv:2+ZhjWrySAwix4p7HNxzjISvdIyT/sCw4YvoxymjTOw=,tag:P7ISJOr+iJ30EZdYXd/pLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
