apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:J1LtrXXoHZ+DWdJGlYx3,iv:7ZYVve/wHb3PV8QxJqFMjW57zyHH2G7YeyHOE+OCjGA=,tag:yTVibuzLjqMYTeY816ivyA==,type:str]
    password: ENC[AES256_GCM,data:TWIGlJZmwmko4UoZRgzmnQ==,iv:9oGMl7QEkwzst557tbcbU5wGa4MuZWH8c552X5cCu+o=,tag:ObPu2MJR+qi3HZxYQr3BKg==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTUpodDZlNWpUMlhNYWtE
            NVVIOSs4bmpveTJvaFpXZDJra2NvV3ZuNnhZCitBUldROGN4V0k0Rk12ejRLYjBq
            a1RraGo2QWwxclkzR05qYUdTQmVSNTAKLS0tIHFTNjRpM0VEQ215RVVuSDRRK0pR
            NExEMXZ6Q0FsYmpXMTJob1RBVElrMzgKehqF1PgUxEpdqQOX+3mtikpyxzkVDWZy
            IBAsN5P6jf+ffVGdNJoocYX9lt2+Fas8DIv5vbtEHD+XnZxTdGGGQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T00:06:28Z"
    mac: ENC[AES256_GCM,data:QhmjeF6i2VxdAl7wq1G8gPzHxYYxjJTauW2pblaBlhSsS43axgOUzTlXO5DpzH8kW/299VClnrxrSVHT6t5yp9jA7owhiMrhHv7epLWLhBI2/3Mk89pqKmRaubuhxB4fvWyQTpU9srh6ucjpfIbutmq9PmX6758YXFkPIv1EyLI=,iv:BRp3FlY61ZuZ/+AkWFXUB4Fo3bNCoR3T276t9U+qnpk=,tag:k2gDy3B5X2I/nxWK+EzYSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
