---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-clamav
  namespace: flux-system
spec:
  path: ./kubernetes/apps/production/development/clamav/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-source
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: clamd
      namespace: development
  interval: 30m
  retryInterval: 1m
  timeout: 10m
