---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kueue
spec:
  values:
    enableCertManager: false
    enablePrometheus: false
    controllerManager:
      replicas: 1
      manager:
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 512Mi
