---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ../../../../base/sbom-operator
  - ./secret.sops.yaml
patches:
  - path: ./sbom-operator-values.yaml
