apiVersion: v1
kind: Secret
metadata:
    name: sbom-operator
type: Opaque
stringData:
    dtrack-api-key: ENC[AES256_GCM,data:4eWJQJeugyWJ1COeSjOd++TfmKgxSf71b1kTmw8Avn2VIju6qEVtj1eKASKI,iv:4otajz28ILtumN7FQhhUvWXH4yWIox5iN9SgXpjTj2s=,tag:NEvZ8z9T/rfsYWo1qQ7rnA==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETHNOa1VTSjAyV1owemkz
            ZjZ0QWtzYzVPaVBGT3NjNVR0QWhMR2oya2tFCnBWb1Vya3VvN2h2TXF1cXpDYmZU
            ZDc5djYxcHl3RlExN2VLd2VnYkkybEkKLS0tIGxqdys0Q3p3ZUxFczJ6THVENUtZ
            MnBJTW82OUVvai9YSWR6YVlEUzBvWE0KYGYWkgfiIH1J9SMIDyJ0+GXTeXES83QM
            R6ywkYQNB4ycDkwPutR99dusgWOShOZaW4rjvOktmfIM4NpuYd4MhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T06:21:25Z"
    mac: ENC[AES256_GCM,data:FFO1AMVu8cCp6YtpWBVVw3ixpRaI58LM0w2HN7NkFzRW8gcteM7F2HNQH67JxD9lRKRp6qMF2cdxddrXWiFlCMvd3mQ/1qOoihgFRibfqEj92uk8RwXLBRkuzHwCQ618nkj6tFOPtElw1GMviSUc1nzJ7XulkvWk4TZNl876xGs=,iv:Sg68xX46+ecgRUvtyJb4y7bR/xr8KQAzL2nf2YgKkvM=,tag:vHr4deD2Rr37NH+5ehQVSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
