---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mariadb
spec:
  sourcePVC: data-bookstack-mariadb-0
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: bookstack-mariadb-restic-config
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: ceph-block
    retain:
      daily: 7
      within: 3d
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mariadb-to-external-home
spec:
  sourcePVC: storage-bookstack-mariadb-0
  trigger:
    schedule: "45 8 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: bookstack-external-home-mariadb-restic-config
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: ceph-block
    retain:
      daily: 7
      weekly: 2
      monthly: 3
