---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: campsearch
resources:
  - ./data-pvc.yaml
  - ./secret.sops.yaml
  - ../../../../base/campquest-v2
patches:
  - path: ./campquest-v2-values.yaml
