# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: campquest-v2-secrets
stringData:
    PB_ENCRYPTION_KEY: ENC[AES256_GCM,data:ANWr+Kks4DrBg7Kbltr4/ofs/7Fb0L4JJlYXQwx5nnI=,iv:5WShBC43nwv1O+BPTYiTptDtYGCcIOux3wpEStjuYjQ=,tag:WfDVI4XLyygarwgmQ3HNhw==,type:str]
    CQ_PUSHOVER_TOKEN: ENC[AES256_GCM,data:7Oh9d/n7t9RL0GOftX5wqVz6wFn0WitsH5dG+Nnk,iv:NazyKoBuJDQVZyQev39CN/pD7JKnJujLP9EMGyZ8O84=,tag:BDHGSoK7LKor6g7P/lleZw==,type:str]
    CQ_PUSHOVER_USER: ENC[AES256_GCM,data:hSkqLfkuIw5s+k6ZGzyAgsAkXx7Ry/qkeaja/6j2,iv:9SofRWzhWDhann73R4jxBO0+5HzubH82voBjoFTLblw=,tag:PuZE/RCpnBoV6x7NmmmShQ==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYXpCTnJTUXordnNhVUgv
            QW9ZdUpQV0F5UDJsWFRNSzZKODI1bEJadlIwCmcwdnFMVUJSRUtWem1ydjBrVjB0
            bTBoc0M2aThrLytXcWFkUkxodUZYaUUKLS0tIFUyaDBkcjZSRXJjVVVqaW1sNjJF
            ZFR4Z0VHYWJVaVkvRE1nSVNNN29lL1EKieW+1cXqxHk26tcfVcgm+8OH/FOe92il
            pDdWFawlWdQFGScl5UrSuE8IC0quHv1VaWzlFEReX2nkKIlSmlzHDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T18:46:33Z"
    mac: ENC[AES256_GCM,data:7QVADaRKSv7RfyWmxnR9HTqQa2WGewKoB64CJyCvPUEnQk8l5U1kD9MJ+tU5QGbT2uUZgLvbDJuNh5wcJyu8evSeLSm0juI9aK0dA1k7RuVIIR6OQwSYjs/Re4K2NqPMUv/fwrjpz+iSit1kf08lhvtvqDPGXFKDqevc0eBM0Tg=,iv:rnZzO0ZXTi3Pj1x8XLcgTWMF45jCWyZMe8NBB6i6aZU=,tag:CejTcLQKz/iVSnda4yOM0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
