# ---
# apiVersion: volsync.backube/v1alpha1
# kind: ReplicationSource
# metadata:
#   name: gitea-data
# spec:
#   sourcePVC: gitea-data
#   trigger:
#     schedule: "0 7 * * *"
#   restic:
#     copyMethod: Snapshot
#     pruneIntervalDays: 7
#     repository: gitea-data-restic-config
#     volumeSnapshotClassName: csi-rbdplugin-snapclass
#     storageClassName: ceph-block
#     retain:
#       daily: 7
#       within: 3d
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: gitea-data-to-external-home
spec:
  sourcePVC: gitea-data
  trigger:
    schedule: "20 8 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: gitea-data-external-home-restic-config
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: ceph-block
    retain:
      daily: 7
      weekly: 2
      monthly: 3
