---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: baserow-data
spec:
  sourcePVC: baserow-data
  trigger:
    schedule: "0 7 * * *"
  restic:
    unlock: "unlock-04-07-2026"
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: baserow-data-restic-config
    volumeSnapshotClassName: longhorn-snapshot-vsc
    storageClassName: longhorn-volsync
    retain:
      daily: 7
      within: 3d
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: baserow-data-to-external-home
spec:
  sourcePVC: baserow-data
  trigger:
    schedule: "10 8 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: baserow-data-external-home-restic-config
    volumeSnapshotClassName: longhorn-snapshot-vsc
    storageClassName: longhorn-volsync
    retain:
      daily: 7
      weekly: 2
      monthly: 3
