---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dependency-track-v5
spec:
  values:
    database:
      jdbcUrl: jdbc:postgresql://dependency-track-v5-postgresql-rw:5432/dtrack?reWriteBatchedInserts=true
      existingSecret:
        name: dependency-track-v5-postgresql-secret
    secretManagement:
      provider: database
      database:
        kek:
          mode: config
          existingSecret:
            name: dependency-track-v5-kek
    fileStorage:
      provider: local
      local:
        storageClassName: ceph-block
        size: 10Gi
    apiServer:
      web:
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            memory: 5Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: dtrack-v5.${SECRET_DOMAIN}
