apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pKWeC5xS9b6mng==,iv:DyUigqnifUdb1rSQg2fvhmYxnbYcVtmXW3/QFJP/Mc0=,tag:XcjroWhkQlqkino6ybcv1g==,type:str]
    password: ENC[AES256_GCM,data:JBfCPUvMr837Sx64FeHLaw==,iv:t6ljzRksUsJ5AqyqiFRwO/DpgbfzJAGA0C2smTHcL40=,tag:zpb7w/+Mbih9QqMziTsKYg==,type:str]
sops:
    age:
        - recipient: age1fl92uj8fwujcphes4cxm82qlztxf4kh6j0d2a9at7alpml266p3sedrvx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZEtVRG1uK3JJZVY5aXpj
            QVhXVWx3MnB3b0xlQitUSkJhWVFUWFhBa0M0CmNaYW1VNjdDQ1h5Ti9OMjE0WllU
            UE5JVSszdG0rRWlvRXdaaSs3MUtOYmcKLS0tIFk5RVRzRjQwSXk5YURCVWYrU0dY
            M0pZQ1FDREJLSXEvSGhURVI4ZkVFaUkKQtJVMDe2KHpIwkANTtBPihge2rxqOrD3
            OVAcQQ333lg9Q6dpFEAaeWKxEsnwdVK5ceuHaiFN+E8kAS20UETx0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T23:36:34Z"
    mac: ENC[AES256_GCM,data:LW8+xVXNHNcqI8QeKHGvMW9UP2y5TrBVvtctuPl6MsVgcc3B46O9qe71X/CJMYtC9AU+VmxsyguwpV452b5E5//cjPPQNnHwunsv36yN1DuOjH4Et3fL7HmyswtJ6AdUNvHUPclcWTsw8LmOdqLwC75+RzX0q0YpTub4jqKY6bE=,iv:GY6WtY8lXtz88EIMv6XTc9zlCTDwfAkG7txLD1+W8QI=,tag:i6MQZPf4XpfntceplWj1FA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
