---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-staging"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "workshops-${SECRET_DOMAIN/./-}-production"
  namespace: networking
spec:
  secretName: "workshops-${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "workshops.${SECRET_DOMAIN}"
  dnsNames:
    - "workshops.${SECRET_DOMAIN}"
    - "*.workshops.${SECRET_DOMAIN}"
