---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kueue
  namespace: flux-system
spec:
  interval: 30m
  url: oci://registry.k8s.io/kueue/charts/kueue
  ref:
    tag: "0.18.2"
